# Generated by Django 6.0 on 2025-12-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rating',
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], default='Petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(default='0 km/l', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
