# Generated by Django 6.0 on 2025-12-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_rating_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20),
        ),
    ]
