# Generated by Django 6.0 on 2025-12-19 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_rating_alter_car_fuel_type_alter_car_mileage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('car', 'user')},
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG')], default='Petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(default='0 km/l', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
