# Generated by Django 6.0 on 2025-12-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='preferred_slot',
            field=models.CharField(max_length=10),
        ),
    ]
