# Generated by Django 6.0 on 2025-12-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_testdrive_status_alter_testdrive_preferred_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='preferred_slot',
            field=models.CharField(choices=[('10-12', '10 AM - 12 PM'), ('12-2', '12 PM - 2 PM'), ('2-4', '2 PM - 4 PM'), ('4-6', '4 PM - 6 PM')], max_length=10),
        ),
    ]
